version: "3.8"

services:
  backend:
    build: ./EmailSender  # Path to backend Dockerfile
    ports:
      - "8080:8080"
  
  frontend:
    build: ./email-sender-frontend # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
