services:
  backend:
    build:
      context: ./EmailSender
      dockerfile: Dockerfile  # Ensure file name matches
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./email-sender-frontend
      dockerfile: Dockerfile  # Ensure file name matches
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
